export const state = {
  xDown: null,
  yDown: null,
  level: 1,
  score: 0,
  enemyScore: 0,
  maxLevel: 4,
  rows: 0,
  columns: 0,
  loading: false,
  playing: false,
  playerSexe: 0,
  borders: [],
  moves: 0,
  canNotMoves: 0,
  maxCanNotMoves: 4,
  borderStops: 0,
  deadStops: 0,
  trapsIntervalTime: 4000,
  debug: false,
};
